### ISSUE TITLE
An example of non-inductive proof

### ISSUE THREAD

**Issue by nponeccop** [groupoid/exe#4]
Translate the following Lean code into a non-inductive subset of Lean, Exe and Om for illustration purposes:

```lean
inductive ee {A : Type} (a : A) : A → Type.{1} := reee : ee a a

definition rffl {A : Type} {a : A} : ee a a := ee.reee a

inductive na : Type :=
| aa : na
| oo : na → na

definition ad : na → na → na := λ(m n : na), na.rec_on n m (λ n, na.oo)

theorem az (m : na) : ee (ad m na.aa) m := rffl
```

**Comment by zraffer** [comment]
As far as we use setoids, we have the built-in equality on every encoded type. Also the encoding should produce a type for the classic propositional equality (shown above). It is intresting to prove the equivalence of the former and the latter.

**Comment by nponeccop** [comment]
Do you plan to go from setoids all the way down to free monoids and ultimately lists? So we for example abandon simpler equalities and use generalized category-theoretical one instead? Will we be able to use e.g. monoid theorems in proofs of theorems about list functions?

The position of @5HT as I understand it is that we don't need that and that we need to keep the design of the standard library as simple as possible, which obviously means avoidance of Category Theory and building the notions we need such as equality directly on top of the logic provided by the type system instead of defining them in a suitable theory of everything (e.g. CT or a set theory).

**Comment by zraffer** [comment]
You are completely right. CT is capable to produce all such kinds of structures, but we don't intend to go so far. EXE is designed to be a functional language with logical capabilities, its implementation in OM uses CT-based ideas for encoding (co)inductive types by limits of setoids.

**Comment by nponeccop** [comment]
Well, we have now [om/priv/normal/Frege/intro][1] which counts as a non-inductive proof.

[1]: https://github.com/groupoid/om/blob/9a9a5f0cddcbf45c9a91801e69eaa9787c148ac3/priv/normal/Frege/intro
